qy:
  eureka:
    url: http://localhost:8000/eureka/     
spring:
  profiles:
    active: dev   
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
