spring:
  application:
    name: qy-user
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: qy-config
  redis:
    database: 2
    host: localhost
    port: 32768
    password: 1qaz@WSX
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 8012
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
