spring:
  application:
    name: qy-user
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: qy-config
server:
  port: 8012
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
