spring:
  application:
    name: qy-user
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8001/
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
