spring:
  application:
    name: qy-user
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8001/
      discovery:
        enabled: false
        service-id: qy-config
server:
  port: 8011
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
